name=UniversalZaloBot
version=0.1.0
author=chunix64
maintainer=chunix64 <linoxolus@gmail.com>
sentence=Arduino Zalo Bot library for multiple different architectures.
paragraph=A Universal Zalo Bot library for arduino devices
category=Communication
url=https://github.com/chunix64/Universal-Arduino-Zalo-Bot
architectures=*
includes=UniversalZaloBot.h
depends=ArduinoJson
